name: 'KSP-AVC Version File Validator'
description: 'Validate the KSP-AVC .version file of your mod against the AVC schema!'
author: 'DasSkelett'
inputs:
  exclude:
    description: 'JSON-array-like list of paths to version files to exclude (supports wildcards), e.g. ["KSP-AVC.version", "GameData/DogeCoinFlag/*.version"]'
    required: false
    default: ''
  only:
    description: 'JSON-array-like list of paths to version files to check exclusively (no wildcard support), e.g. ["GameData/YourMod/YourMod.version"]'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
