FROM python:3.10-alpine as base
COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt
COPY validator/ /validator/
ENTRYPOINT ["python3"]


FROM base as tests
COPY tests/ /tests/
WORKDIR /
CMD ["-m", "unittest", "tests"]
