name: Full Integration Test (Docker)
on:
  push:
    branches:
      - master

jobs:
  full_integration_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Validate files
        with:
          only: '["./tests/workspaces/single-files/valid-remote.version"]'
        uses: DasSkelett/AVC-VersionFileValidator@master
