name: Unit Tests
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests directly
      run: |
        python -m unittest tests
    - name: Run unit tests in Docker container
      run: |
        docker build -f Dockerfile-dev --target tests -t avc-versionfilevalidator .
        docker run avc-versionfilevalidator
